version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/functions"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Asia/Tokyo"
    target-branch: "master"
